### ISSUE TITLE
Cannot resolve http://search:9200

### ISSUE THREAD

**Issue by AndrewC-B** [cisco-ie/tdm#24]
While running `start.sh` I encountered the error shown below. Can you provide any direction to troubleshoot this? Thanks very much! 

```
INFO:root:Populating search database with parsed data.
INFO:root:Acquiring DataPaths from TDM...
INFO:root:Setting up ES...
WARNING:elasticsearch:PUT http://search:9200/datapath [status:N/A request:0.001s]
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/data-I7nS9QO2/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/root/.local/share/virtualenvs/data-I7nS9QO2/lib/python3.7/site-packages/urllib3/util/connection.py", line 57, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name does not resolve
```

**Comment by remingtonc** [comment]
@AndrewC-B Hmm that is unfortunate - can you provide any details on the deployment? Using `docker-compose`? `search` should be resolved to the associated ElasticSearch instance. Were there any errors deploying the `search` container? Would likely be named `tdm_search_1` or something along those lines. If you're trying to use a baremetal ElasticSearch outside of the usual deployment, we will need to edit a couple files but can fix that easily.

**Comment by AndrewC-B** [comment]
Yep, using `docker-compose`. I don't recall seeing any errors during deployment/setup (but that doesn't mean there weren't any - just that there weren't any in the most recent output when `start.sh` exited). Is there a log I could inspect to check?

**Comment by remingtonc** [comment]
@AndrewC-B It does look like the ElasticSearch container went down or didn't start based on that output. `docker logs tdm_search_1` might have logs from the first execution which might be enlightening.

Usually, you would have to restart the entire process, but it's probably time to change that. :) I'm in an area with *terrible* internet connection at the moment, but uglypatching it in branch `etl-search-entry`. I'll ping you when it's tested with docs on how to restart the ETL process, jumping straight to the search stage.

**Comment by AndrewC-B** [comment]
Thanks! The full log is [here](https://gist.github.com/AndrewC-B/5904c7bce9c01c8de6ab691613d8842a). The most obvious issue to me is:

```
ERROR: [1] bootstrap checks failed
[1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2018-12-05T22:40:59,025][INFO ][o.e.n.Node               ] [RL38epu] stopping ...
[2018-12-05T22:40:59,051][INFO ][o.e.n.Node               ] [RL38epu] stopped
[2018-12-05T22:40:59,052][INFO ][o.e.n.Node               ] [RL38epu] closing ...
[2018-12-05T22:40:59,058][INFO ][o.e.n.Node               ] [RL38epu] closed
[2018-12-05T22:40:59,060][INFO ][o.e.x.m.j.p.NativeController] Native controller process has stopped - no new native processes can be started
```

Does this seem like a likely cause of the issues I'm seeing to you? If so, can you recommend steps to rectify? A quick Google search suggests something like this, from [here](https://github.com/elastic/elasticsearch-docker/issues/92):

```
docker-machine ssh
sudo sysctl -w vm.max_map_count=262144
exit
```

**Comment by remingtonc** [comment]
That definitely looks like the culprit. I'm not using Windows which makes it difficult to test, but reading through the thread those commands look like the best bet, or to set `discovery.type=single-node` environment variable for ES to put it into dev mode e.g. [here](https://github.com/cisco-ie/tdm/blob/master/docker-compose.yml#L104).

**Comment by remingtonc** [comment]
@AndrewC-B Regarding loading the data into ES, give this a shot:
```bash
cd tdm/
# git stash if necessary
git pull
git checkout etl-search-entry
docker build -t tdm/etl etl/
docker-compose run --rm etl python main.py --stage search
```

**Comment by AndrewC-B** [comment]
Cheers! I reset overnight. Search now returns results, although All Mappings is still empty (and all the paths I've tried so far say "no datapaths mapped as matches", although some have a "matching datapath"). At a guess, are mapped paths manually defined, and matched paths computer generated? And any ideas about All Mappings being empty?

**Comment by remingtonc** [comment]
Smart :) The mappings are not automated, and the existing mappings are not open-source (yet?) nor is there a public-facing instance for community effort. We're figuring that out. At the moment, we're tackling the human problem and crowd-sourcing, and developing tools to attempt to automate the mappings to then put into TDM.

**Comment by remingtonc** [comment]
Feel free to open a separate issue on the mappings specifically if this is resolved.

**Comment by AndrewC-B** [comment]
Thanks!

**Comment by remingtonc** [comment]
Ah yes, then you would simply change the `sysctl` parameters (no `docker-machine ssh` necessary).

If you have any questions feel free to open an issue or email remcampb@cisco.com (or cisco-ie@cisco.com).
